# Generated by Django 2.1.5 on 2019-01-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190123_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('1', 'Terrible'), ('2', 'Bad'), ('3', 'Neutral'), ('4', 'Good'), ('5', 'Perfect')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='blog.User')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.Mark'),
        ),
    ]
