# Generated by Django 2.1.5 on 2019-01-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190123_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mark',
            field=models.ManyToManyField(related_name='post', through='blog.Mark', to='blog.User', verbose_name='Mark'),
        ),
    ]
